import React, { useState } from 'react';
import { useApp } from '../../services/store';
import { ShieldCheck, Lock, FileText, Camera, Mic, MapPin, AlertCircle } from 'lucide-react';

export const LegalModal: React.FC = () => {
  const { legalModalOpen, setLegalModalOpen } = useApp();
  const [activeTab, setActiveTab] = useState<'privacy' | 'terms' | 'permissions' | 'disclaimer'>('disclaimer');

  if (!legalModalOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fade-in">
      <div className="bg-stone-900 border border-stone-800 rounded-3xl p-6 sm:p-8 max-w-2xl w-full max-h-[85vh] overflow-y-auto shadow-2xl text-stone-200">
        <div className="flex items-center justify-between pb-3 border-b border-stone-800">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400">
                GOVERNANCE & TRANSPARENCY
              </span>
              <h3 className="text-base font-bold text-stone-100">
                Privacy, Permissions & Regulatory Disclaimer
              </h3>
            </div>
          </div>

          <button
            onClick={() => setLegalModalOpen(false)}
            className="text-stone-400 hover:text-stone-200 text-lg leading-none p-1"
          >
            ✕
          </button>
        </div>

        {/* Tab Selector */}
        <div className="flex items-center gap-2 my-4 border-b border-stone-800 pb-2 text-xs">
          <button
            onClick={() => setActiveTab('disclaimer')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition ${
              activeTab === 'disclaimer' ? 'bg-emerald-950 text-emerald-300 border border-emerald-700' : 'text-stone-400'
            }`}
          >
            Core Disclaimer
          </button>
          <button
            onClick={() => setActiveTab('permissions')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition ${
              activeTab === 'permissions' ? 'bg-emerald-950 text-emerald-300 border border-emerald-700' : 'text-stone-400'
            }`}
          >
            Device Permissions
          </button>
          <button
            onClick={() => setActiveTab('privacy')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition ${
              activeTab === 'privacy' ? 'bg-emerald-950 text-emerald-300 border border-emerald-700' : 'text-stone-400'
            }`}
          >
            Privacy Policy
          </button>
          <button
            onClick={() => setActiveTab('terms')}
            className={`px-3 py-1.5 rounded-lg font-semibold transition ${
              activeTab === 'terms' ? 'bg-emerald-950 text-emerald-300 border border-emerald-700' : 'text-stone-400'
            }`}
          >
            Terms of Use
          </button>
        </div>

        {/* Tab Contents */}
        <div className="text-xs text-stone-300 space-y-4 leading-relaxed">
          {activeTab === 'disclaimer' && (
            <div className="space-y-3">
              <div className="p-4 rounded-2xl bg-amber-950/40 border border-amber-800 text-amber-200">
                <strong className="block text-sm font-bold mb-1">DECISION-SUPPORT NOTICE:</strong>
                AgroShield provides decision-support information and does NOT replace professional agricultural, environmental, or regulatory advice.
              </div>
              <p>
                1. <strong>Runoff Risk Estimation: </strong>Values generated by AgroShield represent an estimated mathematical probability of surface sheet runoff based on available weather forecasts, soil textures, and digital elevation slopes.
              </p>
              <p>
                2. <strong>No Direct Chemical Measurement: </strong>AgroShield does NOT directly measure pesticide concentration, groundwater contamination, exact chemical transport, or actual soil microbiome degradation.
              </p>
              <p>
                3. <strong>No Yield or Financial Guarantees: </strong>AgroShield does not guarantee crop yields, pest eradication, or crop profit margins. Farmers must adhere to manufacturer product labels, dosage instructions, protective equipment standards, and guidelines issued by the Department of Agriculture.
              </p>
            </div>
          )}

          {activeTab === 'permissions' && (
            <div className="space-y-3">
              <div className="p-3 rounded-xl bg-stone-950 border border-stone-800 flex items-start gap-3">
                <MapPin className="w-5 h-5 text-emerald-400 mt-0.5 shrink-0" />
                <div>
                  <strong className="text-stone-100 block">Location (GPS) Permissions:</strong>
                  Used solely to associate registered field coordinates with the nearest Doppler weather radar cell and verify in-field soil sampling location.
                </div>
              </div>

              <div className="p-3 rounded-xl bg-stone-950 border border-stone-800 flex items-start gap-3">
                <Camera className="w-5 h-5 text-amber-400 mt-0.5 shrink-0" />
                <div>
                  <strong className="text-stone-100 block">Camera Permissions:</strong>
                  Used exclusively by authorized Field Visitors to capture sample bag QR/barcodes and photograph soil core collection for chain-of-custody traceability. The photo is never used as a substitute for lab spectrometry.
                </div>
              </div>

              <div className="p-3 rounded-xl bg-stone-950 border border-stone-800 flex items-start gap-3">
                <Mic className="w-5 h-5 text-sky-400 mt-0.5 shrink-0" />
                <div>
                  <strong className="text-stone-100 block">Microphone Permissions:</strong>
                  Enables speech-to-text queries in the Farmer Easy Mode voice interface. Audio is not archived or sold.
                </div>
              </div>
            </div>
          )}

          {activeTab === 'privacy' && (
            <div className="space-y-2">
              <p>
                <strong>Data Minimization: </strong>We collect only field boundaries, soil diagnostic results, and crop stage logs necessary to generate hydrological runoff assessments.
              </p>
              <p>
                <strong>Traceability & Security: </strong>All laboratory soil health certificates are stored with immutable hash signatures ensuring authenticity across Mandya agricultural cooperative registries.
              </p>
              <p>
                <strong>User Ownership: </strong>Farmers maintain full ownership of their field data and can export historical seasonal records at any time.
              </p>
            </div>
          )}

          {activeTab === 'terms' && (
            <div className="space-y-2">
              <p>
                By using AgroShield, you acknowledge that all recommendations are advisory and designed to safeguard farm input investments and watershed waterways against untimely rainfall washing.
              </p>
              <p>
                Contact: AgroShield Agricultural Intelligence Cell, Mandya District Agricultural Research Station, Karnataka. Email: <em>support@agroshield.demo</em>
              </p>
            </div>
          )}
        </div>

        <div className="flex justify-end pt-4 mt-4 border-t border-stone-800">
          <button
            onClick={() => setLegalModalOpen(false)}
            className="px-5 py-2 rounded-xl bg-stone-800 hover:bg-stone-700 text-stone-200 text-xs font-bold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
